name: philly-dao
channels:
  - conda-forge
  - nodefaults
dependencies:
# python packages
  - python
  - pip
  - pandas
  - notebook 
  - ipykernel
  - opencv
  - numpy
  - statsmodels
  - ephem
# R packages
# pip installs
  - pip:
    - ipystata
    - psutil
